<div class="language-currency">
    <div class="wrapper-lan-cur">
        <span Class="store-view-selected"></span>
        <ul class="language-currency-content" id="id_language_currency_link">
            <li class="language"><a class="language-links" id="language_link" href="#"></a> <a
                    class="currency-links" id="currency_link" href="#"></a></li>
        </ul>
        <div class="lan-cur-content" id="id_laguage_currency_content"
             style="display:none;">            <?php echo $this->getChildHtml('currency') ?>            <?php echo $this->getChildHtml('store_language') ?>        </div>
    </div>
</div>