<?php

class Magestore_Fbcomment_Model_System_Config_Language
{
    public function toOptionArray()
    {
        $options = array(
					array('value'=>'ca_ES','label'=> Mage::helper('fbcomment')->__('Catalan')),
					array('value'=>'cs_CZ','label'=> Mage::helper('fbcomment')->__('Czech')),
					array('value'=>'cy_GB','label'=> Mage::helper('fbcomment')->__('Welsh')),
					array('value'=>'da_DK','label'=> Mage::helper('fbcomment')->__('Danish')),
					array('value'=>'de_DE','label'=> Mage::helper('fbcomment')->__('German')),
					array('value'=>'eu_ES','label'=> Mage::helper('fbcomment')->__('Basque')),
					array('value'=>'en_PI','label'=> Mage::helper('fbcomment')->__('English (Pirate)')),
					array('value'=>'en_UD','label'=> Mage::helper('fbcomment')->__('English (Upside Down)')),
					array('value'=>'ck_US','label'=> Mage::helper('fbcomment')->__('Cherokee')),
					array('value'=>'en_US','label'=> Mage::helper('fbcomment')->__('English (US)')),
					array('value'=>'es_LA','label'=> Mage::helper('fbcomment')->__('Spanish')),
					array('value'=>'es_CL','label'=> Mage::helper('fbcomment')->__('Spanish (Chile)')),
					array('value'=>'es_CO','label'=> Mage::helper('fbcomment')->__('Spanish (Colombia)')),
					array('value'=>'es_ES','label'=> Mage::helper('fbcomment')->__('Spanish (Spain)')),
					array('value'=>'es_MX','label'=> Mage::helper('fbcomment')->__('Spanish (Mexico)')),
					array('value'=>'es_VE','label'=> Mage::helper('fbcomment')->__('Spanish (Venezuela)')),
					array('value'=>'fb_FI','label'=> Mage::helper('fbcomment')->__('Finnish (test)')),
					array('value'=>'fi_FI','label'=> Mage::helper('fbcomment')->__('Finnish')),
					array('value'=>'fr_FR','label'=> Mage::helper('fbcomment')->__('French (France)')),
					array('value'=>'gl_ES','label'=> Mage::helper('fbcomment')->__('Galician')),
					array('value'=>'hu_HU','label'=> Mage::helper('fbcomment')->__('Hungarian')),
					array('value'=>'it_IT','label'=> Mage::helper('fbcomment')->__('Italian')),
					array('value'=>'ja_JP','label'=> Mage::helper('fbcomment')->__('Japanese')),
					array('value'=>'ko_KR','label'=> Mage::helper('fbcomment')->__('Korean')),
					array('value'=>'nb_NO','label'=> Mage::helper('fbcomment')->__('Norwegian (bokmal)')),
					array('value'=>'nn_NO','label'=> Mage::helper('fbcomment')->__('Norwegian (nynorsk)')),
					array('value'=>'nl_NL','label'=> Mage::helper('fbcomment')->__('Dutch')),
					array('value'=>'pl_PL','label'=> Mage::helper('fbcomment')->__('Polish')),
					array('value'=>'pt_BR','label'=> Mage::helper('fbcomment')->__('Portuguese (Brazil)')),
					array('value'=>'pt_PT','label'=> Mage::helper('fbcomment')->__('Portuguese (Portugal)')),
					array('value'=>'ro_RO','label'=> Mage::helper('fbcomment')->__('Romanian')),
					array('value'=>'ru_RU','label'=> Mage::helper('fbcomment')->__('Russian')),
					array('value'=>'sk_SK','label'=> Mage::helper('fbcomment')->__('Slovak')),
					array('value'=>'sl_SI','label'=> Mage::helper('fbcomment')->__('Slovenian')),
					array('value'=>'sv_SE','label'=> Mage::helper('fbcomment')->__('Swedish')),
					array('value'=>'th_TH','label'=> Mage::helper('fbcomment')->__('Thai')),
					array('value'=>'ku_TR','label'=> Mage::helper('fbcomment')->__('Kurdish')),
					array('value'=>'zh_CN','label'=> Mage::helper('fbcomment')->__('Simplified Chinese (China)')),
					array('value'=>'zh_HK','label'=> Mage::helper('fbcomment')->__('Traditional Chinese (Hong Kong)')),
					array('value'=>'zh_TW','label'=> Mage::helper('fbcomment')->__('Traditional Chinese (Taiwan)')),
					array('value'=>'fb_LT','label'=> Mage::helper('fbcomment')->__('Leet Speak')),
					array('value'=>'af_ZA','label'=> Mage::helper('fbcomment')->__('Afrikaans')),
					array('value'=>'sq_AL','label'=> Mage::helper('fbcomment')->__('Albanian')),
					array('value'=>'hy_AM','label'=> Mage::helper('fbcomment')->__('Armenian')),
					array('value'=>'az_AZ','label'=> Mage::helper('fbcomment')->__('Azeri')),
					array('value'=>'be_BY','label'=> Mage::helper('fbcomment')->__('Belarusian')),
					array('value'=>'bn_IN','label'=> Mage::helper('fbcomment')->__('Bengali')),
					array('value'=>'bs_BA','label'=> Mage::helper('fbcomment')->__('Bosnian')),
					array('value'=>'bg_BG','label'=> Mage::helper('fbcomment')->__('Bulgarian')),
					array('value'=>'hr_HR','label'=> Mage::helper('fbcomment')->__('Croatian')),
					array('value'=>'nl_BE','label'=> Mage::helper('fbcomment')->__('Dutch (Belgie)')),
					array('value'=>'en_GB','label'=> Mage::helper('fbcomment')->__('English (UK)')),
					array('value'=>'eo_EO','label'=> Mage::helper('fbcomment')->__('Esperanto')),
					array('value'=>'et_EE','label'=> Mage::helper('fbcomment')->__('Estonian')),
					array('value'=>'fo_FO','label'=> Mage::helper('fbcomment')->__('Faroese')),
					array('value'=>'fr_CA','label'=> Mage::helper('fbcomment')->__('French (Canada)')),
					array('value'=>'ka_GE','label'=> Mage::helper('fbcomment')->__('Georgian')),
					array('value'=>'el_GR','label'=> Mage::helper('fbcomment')->__('Greek')),
					array('value'=>'gu_IN','label'=> Mage::helper('fbcomment')->__('Gujarati')),
					array('value'=>'hi_IN','label'=> Mage::helper('fbcomment')->__('Hindi')),
					array('value'=>'is_IS','label'=> Mage::helper('fbcomment')->__('Icelandic')),
					array('value'=>'id_ID','label'=> Mage::helper('fbcomment')->__('Indonesian')),
					array('value'=>'ga_IE','label'=> Mage::helper('fbcomment')->__('Irish')),
					array('value'=>'jv_ID','label'=> Mage::helper('fbcomment')->__('Javanese')),
					array('value'=>'kn_IN','label'=> Mage::helper('fbcomment')->__('Kannada')),
					array('value'=>'kk_KZ','label'=> Mage::helper('fbcomment')->__('Kazakh')),
					array('value'=>'la_VA','label'=> Mage::helper('fbcomment')->__('Latin')),
					array('value'=>'lv_LV','label'=> Mage::helper('fbcomment')->__('Latvian')),
					array('value'=>'li_NL','label'=> Mage::helper('fbcomment')->__('Limburgish')),
					array('value'=>'lt_LT','label'=> Mage::helper('fbcomment')->__('Lithuanian')),
					array('value'=>'mk_MK','label'=> Mage::helper('fbcomment')->__('Macedonian')),
					array('value'=>'mg_MG','label'=> Mage::helper('fbcomment')->__('Malagasy')),
					array('value'=>'ms_MY','label'=> Mage::helper('fbcomment')->__('Malay')),
					array('value'=>'mt_MT','label'=> Mage::helper('fbcomment')->__('Maltese')),
					array('value'=>'mr_IN','label'=> Mage::helper('fbcomment')->__('Marathi')),
					array('value'=>'mn_MN','label'=> Mage::helper('fbcomment')->__('Mongolian')),
					array('value'=>'ne_NP','label'=> Mage::helper('fbcomment')->__('Nepali')),
					array('value'=>'pa_IN','label'=> Mage::helper('fbcomment')->__('Punjabi')),
					array('value'=>'rm_CH','label'=> Mage::helper('fbcomment')->__('Romansh')),
					array('value'=>'sa_IN','label'=> Mage::helper('fbcomment')->__('Sanskrit')),
					array('value'=>'sr_RS','label'=> Mage::helper('fbcomment')->__('Serbian')),
					array('value'=>'so_SO','label'=> Mage::helper('fbcomment')->__('Somali')),
					array('value'=>'sw_KE','label'=> Mage::helper('fbcomment')->__('Swahili')),
					array('value'=>'tl_PH','label'=> Mage::helper('fbcomment')->__('Filipino')),
					array('value'=>'ta_IN','label'=> Mage::helper('fbcomment')->__('Tamil')),
					array('value'=>'tt_RU','label'=> Mage::helper('fbcomment')->__('Tatar')),
					array('value'=>'te_IN','label'=> Mage::helper('fbcomment')->__('Telugu')),
					array('value'=>'ml_IN','label'=> Mage::helper('fbcomment')->__('Malayalam')),
					array('value'=>'uk_UA','label'=> Mage::helper('fbcomment')->__('Ukrainian')),
					array('value'=>'uz_UZ','label'=> Mage::helper('fbcomment')->__('Uzbek')),
					array('value'=>'vi_VN','label'=> Mage::helper('fbcomment')->__('Vietnamese')),
					array('value'=>'xh_ZA','label'=> Mage::helper('fbcomment')->__('Xhosa')),
					array('value'=>'zu_ZA','label'=> Mage::helper('fbcomment')->__('Zulu')),
					array('value'=>'km_KH','label'=> Mage::helper('fbcomment')->__('Khmer')),
					array('value'=>'tg_TJ','label'=> Mage::helper('fbcomment')->__('Tajik')),
					array('value'=>'ar_AR','label'=> Mage::helper('fbcomment')->__('Arabic')),
					array('value'=>'he_IL','label'=> Mage::helper('fbcomment')->__('Hebrew')),
					array('value'=>'ur_PK','label'=> Mage::helper('fbcomment')->__('Urdu')),
					array('value'=>'fa_IR','label'=> Mage::helper('fbcomment')->__('Persian')),
					array('value'=>'sy_SY','label'=> Mage::helper('fbcomment')->__('Syriac')),
					array('value'=>'yi_DE','label'=> Mage::helper('fbcomment')->__('Yiddish')),
					array('value'=>'gn_PY','label'=> Mage::helper('fbcomment')->__('Guarani')),
					array('value'=>'qu_PE','label'=> Mage::helper('fbcomment')->__('Quechua')),
					array('value'=>'ay_BO','label'=> Mage::helper('fbcomment')->__('Aymara')),
					array('value'=>'se_NO','label'=> Mage::helper('fbcomment')->__('Northern Sami')),
					array('value'=>'ps_AF','label'=> Mage::helper('fbcomment')->__('Pashto')),
					array('value'=>'tl_ST','label'=> Mage::helper('fbcomment')->__('Klingon')),
				);
		return $options;
    }
}