<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php echo
    $this->getLayout()->createBlock('cms/block')->setBlockId('min_pay')->setCode($_code)->toHtml();?>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('ul#payment_form_pay img.bank-img').each(function(){
            var e = jQuery(this);
            e.click(function(){
                e.addClass('selected');
                jQuery('ul#payment_form_pay img.bank-img').not(e).removeClass('selected');
                var bankclass = e.attr('id');
                jQuery('ul#payment_form_pay li .bank-info').each(function(){
                    if(jQuery(this).hasClass(bankclass)){
                        jQuery(this).show();
                        jQuery("#pay_bank_info").text(jQuery(this).text());
                    }else{
                        jQuery(this).hide();
                    }
                })
            })
        })
    })
</script>
<style>
    ul#payment_form_pay img.bank-img{
        border:1px solid gray;
    }
    ul#payment_form_pay img.bank-img.selected{
        border:1px solid red;
    }
</style>