<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="overview">
        <?php $_collectionSize = 5;//count($_products->getItems()); echo $_collectionSize; ?>
        <?php $i=1; foreach ($_products->getItems() as $_product): ?>
            <div class="bitem">
                <a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"></a>
                <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="ratepd"> <div class="rate rate5"></div> <div class="counpp">5 người đã mua sp</div> </div>
            </div><!-- .bitem-->

            <?php $i++; endforeach; $kol = $_collectionSize; ?>
    </div>
<?php endif; ?>